"""HPO-B continuous-surrogate benchmarks (auto-generated by ``tools/build_hpob_surrogate.py``).

Each class is the SAME HPO-B (search space, dataset) task and mixed-integer search space as the
matching ``HPOB_*`` class, but evaluated by an XGBoost surrogate fit on the pool instead of
nearest-config lookup (see :mod:`._hpob_surrogate_base`). This removes the flatline that discrete
nearest-config lookup causes for continuous-relaxation / mixed-integer BO, giving smooth, non-flat
convergence (matches HPO-B's continuous mode / PFNs4BO). Maximize validation accuracy. Requires
``xgboost`` (``pip install 'bocode[hpobsurr]'``).

Sources:
S. Pineda-Arango, H. S. Jomaa, M. Wistuba, J. Grabocka. HPO-B: A Large-Scale Reproducible Benchmark for Black-Box HPO based on OpenML. NeurIPS Datasets and Benchmarks, 2021. https://github.com/releaunifreiburg/HPO-B
S. Muller, M. Feurer, N. Hollmann, F. Hutter. PFNs4BO: In-Context Learning for Bayesian Optimization. ICML 2023.
"""

from __future__ import annotations

from ._hpob_surrogate_base import HPOBSurrogateProblem


class HPOBSurr_4796_23(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 23), 3 dims."""

    available_dimensions = 3
    task_key = "4796_23"


class HPOBSurr_4796_3549(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 3549), 3 dims."""

    available_dimensions = 3
    task_key = "4796_3549"


class HPOBSurr_4796_3918(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 3918), 3 dims."""

    available_dimensions = 3
    task_key = "4796_3918"


class HPOBSurr_4796_9903(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 9903), 3 dims."""

    available_dimensions = 3
    task_key = "4796_9903"


class HPOBSurr_4796_9906(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 9906), 3 dims."""

    available_dimensions = 3
    task_key = "4796_9906"


class HPOBSurr_4796_9946(HPOBSurrogateProblem):
    """rpart.preproc tuning (HPO-B search space 4796, dataset 9946), 3 dims."""

    available_dimensions = 3
    task_key = "4796_9946"


class HPOBSurr_5527_10101(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 10101), 8 dims."""

    available_dimensions = 8
    task_key = "5527_10101"


class HPOBSurr_5527_145804(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 145804), 8 dims."""

    available_dimensions = 8
    task_key = "5527_145804"


class HPOBSurr_5527_146064(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 146064), 8 dims."""

    available_dimensions = 8
    task_key = "5527_146064"


class HPOBSurr_5527_146065(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 146065), 8 dims."""

    available_dimensions = 8
    task_key = "5527_146065"


class HPOBSurr_5527_31(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 31), 8 dims."""

    available_dimensions = 8
    task_key = "5527_31"


class HPOBSurr_5527_9914(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5527, dataset 9914), 8 dims."""

    available_dimensions = 8
    task_key = "5527_9914"


class HPOBSurr_5636_10101(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 10101), 6 dims."""

    available_dimensions = 6
    task_key = "5636_10101"


class HPOBSurr_5636_145804(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 145804), 6 dims."""

    available_dimensions = 6
    task_key = "5636_145804"


class HPOBSurr_5636_146064(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 146064), 6 dims."""

    available_dimensions = 6
    task_key = "5636_146064"


class HPOBSurr_5636_146065(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 146065), 6 dims."""

    available_dimensions = 6
    task_key = "5636_146065"


class HPOBSurr_5636_31(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 31), 6 dims."""

    available_dimensions = 6
    task_key = "5636_31"


class HPOBSurr_5636_9914(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5636, dataset 9914), 6 dims."""

    available_dimensions = 6
    task_key = "5636_9914"


class HPOBSurr_5859_125923(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 125923), 6 dims."""

    available_dimensions = 6
    task_key = "5859_125923"


class HPOBSurr_5859_31(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 31), 6 dims."""

    available_dimensions = 6
    task_key = "5859_31"


class HPOBSurr_5859_37(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 37), 6 dims."""

    available_dimensions = 6
    task_key = "5859_37"


class HPOBSurr_5859_3902(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 3902), 6 dims."""

    available_dimensions = 6
    task_key = "5859_3902"


class HPOBSurr_5859_9977(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 9977), 6 dims."""

    available_dimensions = 6
    task_key = "5859_9977"


class HPOBSurr_5859_9983(HPOBSurrogateProblem):
    """rpart tuning (HPO-B search space 5859, dataset 9983), 6 dims."""

    available_dimensions = 6
    task_key = "5859_9983"


class HPOBSurr_5889_3918(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 3918), 6 dims."""

    available_dimensions = 6
    task_key = "5889_3918"


class HPOBSurr_5889_9971(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 9971), 6 dims."""

    available_dimensions = 6
    task_key = "5889_9971"


class HPOBSurr_5889_3950(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 3950), 6 dims."""

    available_dimensions = 6
    task_key = "5889_3950"


class HPOBSurr_5889_49(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 49), 6 dims."""

    available_dimensions = 6
    task_key = "5889_49"


class HPOBSurr_5889_31(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 31), 6 dims."""

    available_dimensions = 6
    task_key = "5889_31"


class HPOBSurr_5889_3493(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5889, dataset 3493), 6 dims."""

    available_dimensions = 6
    task_key = "5889_3493"


class HPOBSurr_5891_3492(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 3492), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3492"


class HPOBSurr_5891_3891(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 3891), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3891"


class HPOBSurr_5891_3899(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 3899), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3899"


class HPOBSurr_5891_6566(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 6566), 8 dims."""

    available_dimensions = 8
    task_key = "5891_6566"


class HPOBSurr_5891_9889(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 9889), 8 dims."""

    available_dimensions = 8
    task_key = "5891_9889"


class HPOBSurr_5891_9980(HPOBSurrogateProblem):
    """svm tuning (HPO-B search space 5891, dataset 9980), 8 dims."""

    available_dimensions = 8
    task_key = "5891_9980"


class HPOBSurr_5906_3918(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 3918), 16 dims."""

    available_dimensions = 16
    task_key = "5906_3918"


class HPOBSurr_5906_9971(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 9971), 16 dims."""

    available_dimensions = 16
    task_key = "5906_9971"


class HPOBSurr_5906_3889(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 3889), 16 dims."""

    available_dimensions = 16
    task_key = "5906_3889"


class HPOBSurr_5906_9977(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 9977), 16 dims."""

    available_dimensions = 16
    task_key = "5906_9977"


class HPOBSurr_5906_9970(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 9970), 16 dims."""

    available_dimensions = 16
    task_key = "5906_9970"


class HPOBSurr_5906_3896(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5906, dataset 3896), 16 dims."""

    available_dimensions = 16
    task_key = "5906_3896"


class HPOBSurr_5965_10101(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 10101), 10 dims."""

    available_dimensions = 10
    task_key = "5965_10101"


class HPOBSurr_5965_145836(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 145836), 10 dims."""

    available_dimensions = 10
    task_key = "5965_145836"


class HPOBSurr_5965_3903(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 3903), 10 dims."""

    available_dimensions = 10
    task_key = "5965_3903"


class HPOBSurr_5965_49(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 49), 10 dims."""

    available_dimensions = 10
    task_key = "5965_49"


class HPOBSurr_5965_9889(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9889), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9889"


class HPOBSurr_5965_9914(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9914), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9914"


class HPOBSurr_5965_9946(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9946), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9946"


class HPOBSurr_5970_14951(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 14951), 2 dims."""

    available_dimensions = 2
    task_key = "5970_14951"


class HPOBSurr_5970_34536(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 34536), 2 dims."""

    available_dimensions = 2
    task_key = "5970_34536"


class HPOBSurr_5970_3492(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 3492), 2 dims."""

    available_dimensions = 2
    task_key = "5970_3492"


class HPOBSurr_5970_37(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 37), 2 dims."""

    available_dimensions = 2
    task_key = "5970_37"


class HPOBSurr_5970_49(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 49), 2 dims."""

    available_dimensions = 2
    task_key = "5970_49"


class HPOBSurr_5970_9952(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 5970, dataset 9952), 2 dims."""

    available_dimensions = 2
    task_key = "5970_9952"


class HPOBSurr_5971_10093(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 10093), 16 dims."""

    available_dimensions = 16
    task_key = "5971_10093"


class HPOBSurr_5971_34536(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 34536), 16 dims."""

    available_dimensions = 16
    task_key = "5971_34536"


class HPOBSurr_5971_3954(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 3954), 16 dims."""

    available_dimensions = 16
    task_key = "5971_3954"


class HPOBSurr_5971_43(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 43), 16 dims."""

    available_dimensions = 16
    task_key = "5971_43"


class HPOBSurr_5971_6566(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 6566), 16 dims."""

    available_dimensions = 16
    task_key = "5971_6566"


class HPOBSurr_5971_9970(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 9970), 16 dims."""

    available_dimensions = 16
    task_key = "5971_9970"


class HPOBSurr_6766_10101(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 10101), 2 dims."""

    available_dimensions = 2
    task_key = "6766_10101"


class HPOBSurr_6766_145804(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 145804), 2 dims."""

    available_dimensions = 2
    task_key = "6766_145804"


class HPOBSurr_6766_145953(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 145953), 2 dims."""

    available_dimensions = 2
    task_key = "6766_145953"


class HPOBSurr_6766_146064(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 146064), 2 dims."""

    available_dimensions = 2
    task_key = "6766_146064"


class HPOBSurr_6766_31(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 31), 2 dims."""

    available_dimensions = 2
    task_key = "6766_31"


class HPOBSurr_6766_3903(HPOBSurrogateProblem):
    """glmnet tuning (HPO-B search space 6766, dataset 3903), 2 dims."""

    available_dimensions = 2
    task_key = "6766_3903"


class HPOBSurr_6767_145804(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 145804), 18 dims."""

    available_dimensions = 18
    task_key = "6767_145804"


class HPOBSurr_6767_146064(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 146064), 18 dims."""

    available_dimensions = 18
    task_key = "6767_146064"


class HPOBSurr_6767_146065(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 146065), 18 dims."""

    available_dimensions = 18
    task_key = "6767_146065"


class HPOBSurr_6767_31(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 31), 18 dims."""

    available_dimensions = 18
    task_key = "6767_31"


class HPOBSurr_6767_9914(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 9914), 18 dims."""

    available_dimensions = 18
    task_key = "6767_9914"


class HPOBSurr_6767_9967(HPOBSurrogateProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 9967), 18 dims."""

    available_dimensions = 18
    task_key = "6767_9967"


class HPOBSurr_6794_10101(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 10101), 10 dims."""

    available_dimensions = 10
    task_key = "6794_10101"


class HPOBSurr_6794_145804(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 145804), 10 dims."""

    available_dimensions = 10
    task_key = "6794_145804"


class HPOBSurr_6794_146065(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 146065), 10 dims."""

    available_dimensions = 10
    task_key = "6794_146065"


class HPOBSurr_6794_3(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 3), 10 dims."""

    available_dimensions = 10
    task_key = "6794_3"


class HPOBSurr_6794_31(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 31), 10 dims."""

    available_dimensions = 10
    task_key = "6794_31"


class HPOBSurr_6794_9914(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 6794, dataset 9914), 10 dims."""

    available_dimensions = 10
    task_key = "6794_9914"


class HPOBSurr_7607_9967(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 9967), 9 dims."""

    available_dimensions = 9
    task_key = "7607_9967"


class HPOBSurr_7607_9946(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 9946), 9 dims."""

    available_dimensions = 9
    task_key = "7607_9946"


class HPOBSurr_7607_3903(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 3903), 9 dims."""

    available_dimensions = 9
    task_key = "7607_3903"


class HPOBSurr_7607_3913(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 3913), 9 dims."""

    available_dimensions = 9
    task_key = "7607_3913"


class HPOBSurr_7607_3896(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 3896), 9 dims."""

    available_dimensions = 9
    task_key = "7607_3896"


class HPOBSurr_7607_145976(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7607, dataset 145976), 9 dims."""

    available_dimensions = 9
    task_key = "7607_145976"


class HPOBSurr_7609_125923(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 125923), 9 dims."""

    available_dimensions = 9
    task_key = "7609_125923"


class HPOBSurr_7609_145853(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145853), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145853"


class HPOBSurr_7609_145854(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145854), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145854"


class HPOBSurr_7609_145878(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145878), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145878"


class HPOBSurr_7609_34537(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 34537), 9 dims."""

    available_dimensions = 9
    task_key = "7609_34537"


class HPOBSurr_7609_3903(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 3903), 9 dims."""

    available_dimensions = 9
    task_key = "7609_3903"


class HPOBSurr_7609_9967(HPOBSurrogateProblem):
    """ranger tuning (HPO-B search space 7609, dataset 9967), 9 dims."""

    available_dimensions = 9
    task_key = "7609_9967"
