"""FixedHPO-B benchmarks — discrete HPO-B configuration pools (one per task).

Auto-generated by ``tools/build_hpob_tables.py``. Each class is a discrete pool of
real evaluated configurations for one HPO-B (search space, OpenML dataset) task
(see :mod:`._hpob_base`), maximize validation accuracy. Class name encodes the HPO-B
search-space id and dataset id; the model family is in each docstring.

Sources:
S. Pineda-Arango, H. S. Jomaa, M. Wistuba, J. Grabocka. HPO-B: A Large-Scale Reproducible Benchmark for Black-Box HPO based on OpenML. Advances in Neural Information Processing Systems Datasets and Benchmarks, 2021. https://github.com/releaunifreiburg/HPO-B
S. Gabriel. Fixed HPO-B. https://github.com/SamuelGabriel/FixedHPO-B
"""

from __future__ import annotations

from ._hpob_base import HPOBProblem


class HPOB_5527_10101(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 10101), 8 dims."""

    available_dimensions = 8
    task_key = "5527_10101"


class HPOB_5527_145804(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 145804), 8 dims."""

    available_dimensions = 8
    task_key = "5527_145804"


class HPOB_5527_146064(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 146064), 8 dims."""

    available_dimensions = 8
    task_key = "5527_146064"


class HPOB_5527_146065(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 146065), 8 dims."""

    available_dimensions = 8
    task_key = "5527_146065"


class HPOB_5527_31(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 31), 8 dims."""

    available_dimensions = 8
    task_key = "5527_31"


class HPOB_5527_9914(HPOBProblem):
    """svm tuning (HPO-B search space 5527, dataset 9914), 8 dims."""

    available_dimensions = 8
    task_key = "5527_9914"


class HPOB_5636_10101(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 10101), 6 dims."""

    available_dimensions = 6
    task_key = "5636_10101"


class HPOB_5636_145804(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 145804), 6 dims."""

    available_dimensions = 6
    task_key = "5636_145804"


class HPOB_5636_146064(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 146064), 6 dims."""

    available_dimensions = 6
    task_key = "5636_146064"


class HPOB_5636_146065(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 146065), 6 dims."""

    available_dimensions = 6
    task_key = "5636_146065"


class HPOB_5636_31(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 31), 6 dims."""

    available_dimensions = 6
    task_key = "5636_31"


class HPOB_5636_9914(HPOBProblem):
    """rpart tuning (HPO-B search space 5636, dataset 9914), 6 dims."""

    available_dimensions = 6
    task_key = "5636_9914"


class HPOB_5859_125923(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 125923), 6 dims."""

    available_dimensions = 6
    task_key = "5859_125923"


class HPOB_5859_31(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 31), 6 dims."""

    available_dimensions = 6
    task_key = "5859_31"


class HPOB_5859_37(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 37), 6 dims."""

    available_dimensions = 6
    task_key = "5859_37"


class HPOB_5859_3902(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 3902), 6 dims."""

    available_dimensions = 6
    task_key = "5859_3902"


class HPOB_5859_9977(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 9977), 6 dims."""

    available_dimensions = 6
    task_key = "5859_9977"


class HPOB_5859_9983(HPOBProblem):
    """rpart tuning (HPO-B search space 5859, dataset 9983), 6 dims."""

    available_dimensions = 6
    task_key = "5859_9983"


class HPOB_5891_3492(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 3492), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3492"


class HPOB_5891_3891(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 3891), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3891"


class HPOB_5891_3899(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 3899), 8 dims."""

    available_dimensions = 8
    task_key = "5891_3899"


class HPOB_5891_6566(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 6566), 8 dims."""

    available_dimensions = 8
    task_key = "5891_6566"


class HPOB_5891_9889(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 9889), 8 dims."""

    available_dimensions = 8
    task_key = "5891_9889"


class HPOB_5891_9980(HPOBProblem):
    """svm tuning (HPO-B search space 5891, dataset 9980), 8 dims."""

    available_dimensions = 8
    task_key = "5891_9980"


class HPOB_5965_10101(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 10101), 10 dims."""

    available_dimensions = 10
    task_key = "5965_10101"


class HPOB_5965_145836(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 145836), 10 dims."""

    available_dimensions = 10
    task_key = "5965_145836"


class HPOB_5965_3903(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 3903), 10 dims."""

    available_dimensions = 10
    task_key = "5965_3903"


class HPOB_5965_49(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 49), 10 dims."""

    available_dimensions = 10
    task_key = "5965_49"


class HPOB_5965_9889(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9889), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9889"


class HPOB_5965_9914(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9914), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9914"


class HPOB_5965_9946(HPOBProblem):
    """ranger tuning (HPO-B search space 5965, dataset 9946), 10 dims."""

    available_dimensions = 10
    task_key = "5965_9946"


class HPOB_5970_14951(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 14951), 2 dims."""

    available_dimensions = 2
    task_key = "5970_14951"


class HPOB_5970_34536(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 34536), 2 dims."""

    available_dimensions = 2
    task_key = "5970_34536"


class HPOB_5970_3492(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 3492), 2 dims."""

    available_dimensions = 2
    task_key = "5970_3492"


class HPOB_5970_37(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 37), 2 dims."""

    available_dimensions = 2
    task_key = "5970_37"


class HPOB_5970_49(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 49), 2 dims."""

    available_dimensions = 2
    task_key = "5970_49"


class HPOB_5970_9952(HPOBProblem):
    """xgboost tuning (HPO-B search space 5970, dataset 9952), 2 dims."""

    available_dimensions = 2
    task_key = "5970_9952"


class HPOB_5971_10093(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 10093), 16 dims."""

    available_dimensions = 16
    task_key = "5971_10093"


class HPOB_5971_34536(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 34536), 16 dims."""

    available_dimensions = 16
    task_key = "5971_34536"


class HPOB_5971_3954(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 3954), 16 dims."""

    available_dimensions = 16
    task_key = "5971_3954"


class HPOB_5971_43(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 43), 16 dims."""

    available_dimensions = 16
    task_key = "5971_43"


class HPOB_5971_6566(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 6566), 16 dims."""

    available_dimensions = 16
    task_key = "5971_6566"


class HPOB_5971_9970(HPOBProblem):
    """xgboost tuning (HPO-B search space 5971, dataset 9970), 16 dims."""

    available_dimensions = 16
    task_key = "5971_9970"


class HPOB_6766_10101(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 10101), 2 dims."""

    available_dimensions = 2
    task_key = "6766_10101"


class HPOB_6766_145804(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 145804), 2 dims."""

    available_dimensions = 2
    task_key = "6766_145804"


class HPOB_6766_145953(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 145953), 2 dims."""

    available_dimensions = 2
    task_key = "6766_145953"


class HPOB_6766_146064(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 146064), 2 dims."""

    available_dimensions = 2
    task_key = "6766_146064"


class HPOB_6766_31(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 31), 2 dims."""

    available_dimensions = 2
    task_key = "6766_31"


class HPOB_6766_3903(HPOBProblem):
    """ranger tuning (HPO-B search space 6766, dataset 3903), 2 dims."""

    available_dimensions = 2
    task_key = "6766_3903"


class HPOB_6767_145804(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 145804), 18 dims."""

    available_dimensions = 18
    task_key = "6767_145804"


class HPOB_6767_146064(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 146064), 18 dims."""

    available_dimensions = 18
    task_key = "6767_146064"


class HPOB_6767_146065(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 146065), 18 dims."""

    available_dimensions = 18
    task_key = "6767_146065"


class HPOB_6767_31(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 31), 18 dims."""

    available_dimensions = 18
    task_key = "6767_31"


class HPOB_6767_9914(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 9914), 18 dims."""

    available_dimensions = 18
    task_key = "6767_9914"


class HPOB_6767_9967(HPOBProblem):
    """xgboost tuning (HPO-B search space 6767, dataset 9967), 18 dims."""

    available_dimensions = 18
    task_key = "6767_9967"


class HPOB_6794_10101(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 10101), 10 dims."""

    available_dimensions = 10
    task_key = "6794_10101"


class HPOB_6794_145804(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 145804), 10 dims."""

    available_dimensions = 10
    task_key = "6794_145804"


class HPOB_6794_146065(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 146065), 10 dims."""

    available_dimensions = 10
    task_key = "6794_146065"


class HPOB_6794_3(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 3), 10 dims."""

    available_dimensions = 10
    task_key = "6794_3"


class HPOB_6794_31(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 31), 10 dims."""

    available_dimensions = 10
    task_key = "6794_31"


class HPOB_6794_9914(HPOBProblem):
    """ranger tuning (HPO-B search space 6794, dataset 9914), 10 dims."""

    available_dimensions = 10
    task_key = "6794_9914"


class HPOB_7609_125923(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 125923), 9 dims."""

    available_dimensions = 9
    task_key = "7609_125923"


class HPOB_7609_145853(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145853), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145853"


class HPOB_7609_145854(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145854), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145854"


class HPOB_7609_145878(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 145878), 9 dims."""

    available_dimensions = 9
    task_key = "7609_145878"


class HPOB_7609_34537(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 34537), 9 dims."""

    available_dimensions = 9
    task_key = "7609_34537"


class HPOB_7609_3903(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 3903), 9 dims."""

    available_dimensions = 9
    task_key = "7609_3903"


class HPOB_7609_9967(HPOBProblem):
    """ranger tuning (HPO-B search space 7609, dataset 9967), 9 dims."""

    available_dimensions = 9
    task_key = "7609_9967"
