"""TuRBO: Trust-Region Bayesian Optimization (single trust region, TuRBO-1).

Implements the trust-region BO of Eriksson et al., 2019. A local GP is fit inside
an axis-aligned trust region centered on the best observation; the region grows
after consecutive successes and shrinks after failures, and is restarted when it
collapses. This local strategy scales to higher dimensions far better than global
EI. Candidates are generated by a perturbation/Thompson-sampling scheme within the
trust region.

Run::

    python -m algorithms.single_obj.turbo --problem Rover --init 20 --iters 100
    python -m algorithms.single_obj.turbo --dataset CrossedBarrel --init 10 --iters 40

Sources:
D. Eriksson, M. Pearce, J. Gardner, R. D. Turner, and M. Poloczek. Scalable Global Optimization via Local Bayesian Optimization. NeurIPS 2019. https://arxiv.org/abs/1910.01739
BoTorch TuRBO tutorial: https://botorch.org/docs/tutorials/turbo_1
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass

import torch
from botorch.acquisition import qExpectedImprovement
from botorch.sampling import SobolQMCNormalSampler
from torch.quasirandom import SobolEngine

from .._bo_utils import (
    DTYPE,
    DatasetObjective,
    ProblemObjective,
    Result,
    add_common_args,
    finalize,
    fit_gp,
    initial_design,  # noqa: E501
    make_problem,
    set_seed,
)


@dataclass
class TrustRegion:
    """State for a single TuRBO trust region (lengths and success/failure counts)."""

    dim: int
    length: float = 0.8
    length_min: float = 0.5**7
    length_max: float = 1.6
    success_counter: int = 0
    failure_counter: int = 0
    success_tolerance: int = 3
    restart: bool = False

    def __post_init__(self):
        # Standard TuRBO failure tolerance: scales with dimension.
        self.failure_tolerance = math.ceil(max(4.0, float(self.dim)))

    def update(self, improved: bool) -> None:
        if improved:
            self.success_counter += 1
            self.failure_counter = 0
        else:
            self.success_counter = 0
            self.failure_counter += 1
        if self.success_counter == self.success_tolerance:
            self.length = min(2.0 * self.length, self.length_max)
            self.success_counter = 0
        elif self.failure_counter == self.failure_tolerance:
            self.length /= 2.0
            self.failure_counter = 0
        if self.length < self.length_min:
            self.restart = True


def _candidates_in_region(model, X, Y, length, n_candidates, seed):
    """Generate candidate points inside the trust region around the best point.

    Uses the TuRBO perturbation mask: each candidate copies the best point and
    perturbs a random subset of dimensions within a box of side ``length``.
    """
    dim = X.shape[-1]
    x_center = X[Y.argmax()].clone()
    weights = torch.ones(dim, dtype=DTYPE)  # isotropic (lengthscales optional)
    tr_lb = torch.clamp(x_center - weights * length / 2.0, 0.0, 1.0)
    tr_ub = torch.clamp(x_center + weights * length / 2.0, 0.0, 1.0)

    sobol = SobolEngine(dim, scramble=True, seed=seed)
    pert = sobol.draw(n_candidates).to(DTYPE)
    pert = tr_lb + (tr_ub - tr_lb) * pert

    prob_perturb = min(20.0 / dim, 1.0)
    mask = torch.rand(n_candidates, dim, dtype=DTYPE) <= prob_perturb
    # ensure at least one perturbed dimension per candidate
    ind = torch.where(mask.sum(dim=1) == 0)[0]
    mask[ind, torch.randint(0, dim, (len(ind),))] = True

    X_cand = x_center.expand(n_candidates, dim).clone()
    X_cand[mask] = pert[mask]
    return X_cand


def optimize_problem(
    problem, n_init: int = 20, iters: int = 100, seed: int = 0, batch: int = 1
) -> Result:
    """Continuous TuRBO-1 over the unit cube for a problem."""
    set_seed(seed)
    obj = ProblemObjective(problem)
    res = Result("turbo", type(problem).__name__, seed, acquisition_function="qEI")

    def restart_data():
        X = initial_design(n_init, obj.dim, seed)
        return X, obj(X)

    train_X, train_Y = restart_data()
    best = train_Y.max().item()
    res.start(best)

    tr = TrustRegion(dim=obj.dim)
    evals = 0
    while evals < iters:
        model = fit_gp(train_X, train_Y)
        n_cand = min(5000, max(2000, 200 * obj.dim))
        X_cand = _candidates_in_region(
            model, train_X, train_Y, tr.length, n_cand, seed + evals
        )
        sampler = SobolQMCNormalSampler(sample_shape=torch.Size([256]))
        acqf = qExpectedImprovement(model=model, best_f=train_Y.max(), sampler=sampler)
        with torch.no_grad():
            scores = acqf(X_cand.unsqueeze(1))
        cand = X_cand[scores.topk(batch).indices]

        y = obj(cand)
        improved = y.max().item() > train_Y.max().item() + 1e-3 * abs(
            train_Y.max().item()
        )
        train_X = torch.cat([train_X, cand], dim=0)
        train_Y = torch.cat([train_Y, y], dim=0)
        tr.update(improved)

        for j in range(cand.shape[0]):
            best = max(best, y[j].item())
            res.record(best)
            evals += 1
            if evals >= iters:
                break

        if tr.restart and evals < iters:
            new_X, new_Y = restart_data()
            train_X, train_Y = new_X, new_Y
            tr = TrustRegion(dim=obj.dim)
            for _ in range(min(n_init, iters - evals)):
                best = max(best, new_Y.max().item())
                res.record(best)
                evals += 1
    return res


def optimize_dataset(
    dataset_problem, n_init: int = 10, iters: int = 50, seed: int = 0
) -> Result:
    """Discrete TuRBO over a candidate pool: restrict EI to candidates in the region."""
    set_seed(seed)
    data = DatasetObjective(dataset_problem)
    res = Result(
        "turbo", type(dataset_problem).__name__, seed, acquisition_function="qEI"
    )

    perm = torch.randperm(data.n_candidates)
    observed = perm[:n_init].tolist()
    best = data.select(torch.tensor(observed)).max().item()
    res.start(best)

    tr = TrustRegion(dim=data.dim)
    for _ in range(iters):
        obs = torch.tensor(observed)
        model = fit_gp(data.X[obs], data.Y[obs])
        x_center = data.X[obs][data.Y[obs].argmax()]
        within = ((data.X - x_center).abs() <= tr.length / 2.0).all(dim=1)
        mask = within.clone()
        mask[obs] = False
        pool_idx = mask.nonzero(as_tuple=True)[0]
        if pool_idx.numel() == 0:  # region empty: fall back to all unobserved
            mask = torch.ones(data.n_candidates, dtype=torch.bool)
            mask[obs] = False
            pool_idx = mask.nonzero(as_tuple=True)[0]
            if pool_idx.numel() == 0:
                break

        sampler = SobolQMCNormalSampler(sample_shape=torch.Size([256]))
        acqf = qExpectedImprovement(
            model=model, best_f=data.Y[obs].max(), sampler=sampler
        )
        with torch.no_grad():
            scores = acqf(data.X[pool_idx].unsqueeze(1))
        choice = pool_idx[scores.argmax()].item()

        y = data.select(torch.tensor(choice)).item()
        tr.update(y > best + 1e-9)
        observed.append(choice)
        best = max(best, y)
        res.record(best)
        if tr.restart:
            tr = TrustRegion(dim=data.dim)
    return res


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--problem")
    group.add_argument("--dataset")
    parser.add_argument("--init", type=int, default=20)
    parser.add_argument("--iters", type=int, default=100)
    add_common_args(parser)
    args = parser.parse_args()

    if args.problem:
        res = optimize_problem(
            make_problem(args.problem, args), args.init, args.iters, args.seed
        )
    else:
        res = optimize_dataset(
            make_problem(args.dataset, args), args.init, args.iters, args.seed
        )
    finalize(res, args)


if __name__ == "__main__":
    main()
