"""Build the FixedHPO-B data (hpob_data.npz) + the HPOB.py problem classes.

Task selection (per HPO-B-v3 search space):

* primary — every meta-test task with at least 1000 evaluations (a fixed
  2000-config subsample when larger), as recommended by FixedHPO-B;
* fallback — four mixed search spaces (4796, 5889, 5906, 7607) have *no* task
  with 1000+ evaluations in any split, but must still be covered (traverse ALL
  mixed spaces). For those we take the 6 largest pools with at least 100
  evaluations (HPO-B-v2's own floor) across meta-train/validation/test;
* skipped — search space 5860 (glmnet: alpha, lambda) is purely continuous AND
  has no 1000+-eval task, so it is not added. Its twin glmnet spaces 5970/6766
  qualify under the primary rule and are kept (they register as continuous,
  not mixed).

Following FixedHPO-B, the log-scale dimensions HPO-B forgot to transform
(``LOG_FIXED_DIMS`` in ``_hpob_base``) are log-transformed and re-min-max
normalized per task before storing.

Everything lands in a single compressed
``bocode/opt_problems/hpo/data/hpob_data.npz`` (key ``"<space>_<dataset>"`` ->
``(n, d+1)`` float32: d features then accuracy), and ``hpo/HPOB.py`` is
(re)generated with one problem class per task. One-time:

    curl -L "https://github.com/sebastianpinedaar/hpo-data/raw/refs/heads/main/hpob-data.zip?download=" -o hpob-data.zip
    unzip hpob-data.zip
    python tools/build_hpob_tables.py --data /path/to/hpob-data
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
import sys  # noqa: E402

sys.path.insert(0, str(ROOT))

from bocode.opt_problems.hpo._hpob_base import LOG_FIXED_DIMS  # noqa: E402

MIN_EVALS = 1000
MAX_POOL = 2000
FALLBACK_MIN_EVALS = 100
FALLBACK_MAX_TASKS = 6

# HPO-B-v3 search-space id -> model family (standard HPO-B mapping; for the docstring).
SPACE_MODEL = {
    "4796": "rpart.preproc",
    "5527": "svm",
    "5636": "rpart",
    "5859": "rpart",
    "5860": "glmnet",
    "5889": "ranger",
    "5891": "svm",
    "5906": "xgboost",
    "5965": "ranger",
    "5970": "glmnet",
    "5971": "xgboost",
    "6766": "glmnet",
    "6767": "xgboost",
    "6794": "ranger",
    "7607": "ranger",
    "7609": "ranger",
}

# glmnet spaces (alpha, lambda) have no categorical/integer dimension at all.
PURE_CONTINUOUS_SPACES = {"5860", "5970", "6766"}

_MODULE_HEADER = '''"""FixedHPO-B benchmarks — discrete HPO-B configuration pools (one per task).

Auto-generated by ``tools/build_hpob_tables.py``. Each class is a discrete pool of
real evaluated configurations for one HPO-B (search space, OpenML dataset) task
(see :mod:`._hpob_base`), maximize validation accuracy. Class name encodes the HPO-B
search-space id and dataset id; the model family is in each docstring. All 13 mixed
HPO-B-v3 search spaces are covered (plus the two glmnet spaces that meet the
1000-evaluation bar); only the purely continuous glmnet space 5860 is skipped.

Sources:
S. Pineda-Arango, H. S. Jomaa, M. Wistuba, J. Grabocka. HPO-B: A Large-Scale Reproducible Benchmark for Black-Box HPO based on OpenML. Advances in Neural Information Processing Systems Datasets and Benchmarks, 2021. https://github.com/releaunifreiburg/HPO-B
S. Gabriel. Fixed HPO-B. https://github.com/SamuelGabriel/FixedHPO-B
"""

from __future__ import annotations

from ._hpob_base import HPOBProblem
'''


def _apply_log_fix(space: str, X: np.ndarray) -> np.ndarray:
    """FixedHPO-B: log the dimensions HPO-B missed, re-normalize to [0, 1]."""
    idx = LOG_FIXED_DIMS.get(space, [])
    if not idx:
        return X
    X = X.copy()
    logged = np.log(X[:, idx] + 1e-6)
    lo = logged.min(axis=0)
    rng = logged.max(axis=0) - lo
    rng = np.where(rng > 0, rng, 1.0)
    X[:, idx] = (logged - lo) / rng
    return X


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--data",
        required=True,
        help="path to the hpob-data directory (containing meta-*-dataset.json)",
    )
    ap.add_argument(
        "--max-pool",
        type=int,
        default=0,
        help="cap each task's pool to this many configs (random subsample, seed 0). "
        "0 (default) = use the FULL recorded pool per task (FixedHPO-B uses the full pools; "
        "the old 2000 cap was a bocode size/speed choice, not the protocol).",
    )
    args = ap.parse_args()
    data_dir = Path(args.data)
    global MAX_POOL
    MAX_POOL = args.max_pool

    splits = {
        split: json.load(open(data_dir / f"meta-{split}-dataset.json"))
        for split in ("test", "train", "validation")
    }

    # ---- task selection --------------------------------------------------
    selected: list[tuple[str, str]] = []  # (space, dataset) -> pulled from any split
    pools: dict[tuple[str, str], tuple[np.ndarray, np.ndarray]] = {}
    for space in sorted(SPACE_MODEL):
        primary = sorted(
            ds
            for ds, v in splits["test"].get(space, {}).items()
            if len(v["y"]) >= MIN_EVALS
        )
        if primary:
            for ds in primary:
                v = splits["test"][space][ds]
                pools[(space, ds)] = (
                    np.asarray(v["X"], float),
                    np.asarray(v["y"], float).ravel(),
                )
                selected.append((space, ds))
            continue
        if space in PURE_CONTINUOUS_SPACES:
            print(
                f"skip space {space} ({SPACE_MODEL[space]}): purely continuous "
                f"(alpha, lambda) and no task with >= {MIN_EVALS} evaluations"
            )
            continue
        # Mixed space with no 1000+-eval task anywhere: relax to the largest pools.
        candidates = []
        for split, blob in splits.items():
            for ds, v in blob.get(space, {}).items():
                n = len(v["y"])
                if n >= FALLBACK_MIN_EVALS:
                    candidates.append((-n, int(ds), ds, split))
        candidates.sort()
        take = candidates[:FALLBACK_MAX_TASKS]
        print(
            f"space {space} ({SPACE_MODEL[space]}): no >= {MIN_EVALS}-eval task; "
            f"falling back to {len(take)} largest pools "
            f"({[(ds, -negn, split) for negn, _, ds, split in take]})"
        )
        for _negn, _, ds, split in take:
            v = splits[split][space][ds]
            pools[(space, ds)] = (
                np.asarray(v["X"], float),
                np.asarray(v["y"], float).ravel(),
            )
            selected.append((space, ds))

    # ---- build tables ----------------------------------------------------
    out = ROOT / "bocode/opt_problems/hpo/data"
    out.mkdir(parents=True, exist_ok=True)
    tables, tasks = {}, []
    for space, dataset in selected:
        X, y = pools[(space, dataset)]
        X = _apply_log_fix(space, X)
        dim = X.shape[1]
        if MAX_POOL and len(X) > MAX_POOL:          # 0 => keep the FULL pool (default)
            rng = np.random.RandomState(0)
            idx = rng.choice(len(X), MAX_POOL, replace=False)
            X, y = X[idx], y[idx]
        tables[f"{space}_{dataset}"] = np.column_stack([X, y]).astype(np.float32)
        tasks.append((space, dataset, dim))
    np.savez_compressed(out / "hpob_data.npz", **tables)

    # ---- generate problem classes ----------------------------------------
    src = [_MODULE_HEADER]
    for space, dataset, dim in tasks:
        model = SPACE_MODEL.get(space, "model")
        src.append(
            f"\n\nclass HPOB_{space}_{dataset}(HPOBProblem):\n"
            f'    """{model} tuning (HPO-B search space {space}, dataset {dataset}), {dim} dims."""\n\n'
            f"    available_dimensions = {dim}\n"
            f'    task_key = "{space}_{dataset}"\n'
        )
    (ROOT / "bocode/opt_problems/hpo/HPOB.py").write_text("".join(src))
    print(f"wrote hpob_data.npz + {len(tasks)} HPO-B classes")


if __name__ == "__main__":
    main()
