"""Generate ``bocode/opt_problems/hpo/HPOBSurrogate.py`` from ``HPOB.py``.

The continuous-surrogate HPO-B pools (``HPOBSurr_*``) are the SAME tasks / mixed-integer search
spaces as the discrete ``HPOB_*`` pools (same ``task_key``, ``available_dimensions``, docstring),
but subclass :class:`HPOBSurrogateProblem` so ``evaluate`` queries an XGBoost surrogate over the
pool instead of nearest-config lookup (smooth, non-flat landscape for continuous / mixed-int BO).

So this script just rewrites the class list from ``HPOB.py`` (which is itself generated by
``build_hpob_tables.py`` from ``hpob_data.npz``). Re-run after ``build_hpob_tables.py`` changes,
then ``tools/generate_registry.py`` and ``tools/generate_metadata.py``.
"""

from __future__ import annotations

import re
from pathlib import Path

HPO = Path(__file__).resolve().parent.parent / "bocode" / "opt_problems" / "hpo"

_HEADER = '''"""HPO-B continuous-surrogate benchmarks (auto-generated by ``tools/build_hpob_surrogate.py``).

Each class is the SAME HPO-B (search space, dataset) task and mixed-integer search space as the
matching ``HPOB_*`` class, but evaluated by an XGBoost surrogate fit on the pool instead of
nearest-config lookup (see :mod:`._hpob_surrogate_base`). This removes the flatline that discrete
nearest-config lookup causes for continuous-relaxation / mixed-integer BO, giving smooth, non-flat
convergence (matches HPO-B's continuous mode / PFNs4BO). Maximize validation accuracy. Requires
``xgboost`` (``pip install 'bocode[hpobsurr]'``).

Sources:
S. Pineda-Arango, H. S. Jomaa, M. Wistuba, J. Grabocka. HPO-B: A Large-Scale Reproducible Benchmark for Black-Box HPO based on OpenML. NeurIPS Datasets and Benchmarks, 2021. https://github.com/releaunifreiburg/HPO-B
S. Muller, M. Feurer, N. Hollmann, F. Hutter. PFNs4BO: In-Context Learning for Bayesian Optimization. ICML 2023.
"""'''


def main() -> None:
    src = (HPO / "HPOB.py").read_text()
    out = src
    out = re.sub(r'^""".*?"""', _HEADER, out, count=1, flags=re.DOTALL)
    out = out.replace(
        "from ._hpob_base import HPOBProblem",
        "from ._hpob_surrogate_base import HPOBSurrogateProblem",
    )
    out = re.sub(
        r"class HPOB_([0-9_]+)\(HPOBProblem\):",
        r"class HPOBSurr_\1(HPOBSurrogateProblem):",
        out,
    )
    (HPO / "HPOBSurrogate.py").write_text(out)
    print(f"wrote HPOBSurrogate.py with {out.count('class HPOBSurr_')} classes")


if __name__ == "__main__":
    main()
