"""Build the FixedHPO-B data (hpob_data.npz) + the HPOB.py problem classes.

Extracts every HPO-B meta-test (search-space, dataset) task with at least 1000
evaluations (a fixed 2000-config subsample when larger) into a single compressed
``bocode/opt_problems/hpo/data/hpob_data.npz`` (key ``"<space>_<dataset>"`` ->
``(n, d+1)`` float32: d features then accuracy), and (re)generates ``hpo/HPOB.py``
with one problem class per task. The HPO-B search space is already [0,1]^d. One-time:

    curl -L "https://github.com/sebastianpinedaar/hpo-data/raw/refs/heads/main/hpob-data.zip?download=" -o hpob-data.zip
    unzip hpob-data.zip
    python tools/build_hpob_tables.py --data /path/to/hpob-data/meta-test-dataset.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

MIN_EVALS = 1000
MAX_POOL = 2000

# HPO-B search-space id -> model family (standard HPO-B mapping; for the docstring).
SPACE_MODEL = {
    "4796": "rpart.preproc", "5527": "svm", "5636": "rpart", "5859": "rpart",
    "5860": "glmnet", "5889": "rpart", "5891": "svm", "5906": "xgboost",
    "5965": "ranger", "5970": "xgboost", "5971": "xgboost", "6766": "ranger",
    "6767": "xgboost", "6794": "ranger", "7607": "ranger", "7609": "ranger",
}

_MODULE_HEADER = '''"""FixedHPO-B benchmarks — discrete HPO-B configuration pools (one per task).

Auto-generated by ``tools/build_hpob_tables.py``. Each class is a discrete pool of
real evaluated configurations for one HPO-B (search space, OpenML dataset) task
(see :mod:`._hpob_base`), maximize validation accuracy. Class name encodes the HPO-B
search-space id and dataset id; the model family is in each docstring.

Sources:
S. Pineda-Arango, H. S. Jomaa, M. Wistuba, J. Grabocka. HPO-B: A Large-Scale Reproducible Benchmark for Black-Box HPO based on OpenML. Advances in Neural Information Processing Systems Datasets and Benchmarks, 2021. https://github.com/releaunifreiburg/HPO-B
S. Gabriel. Fixed HPO-B. https://github.com/SamuelGabriel/FixedHPO-B
"""

from __future__ import annotations

from ._hpob_base import HPOBProblem
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", required=True, help="path to meta-test-dataset.json")
    args = ap.parse_args()

    data = json.load(open(args.data))
    root = Path(__file__).resolve().parent.parent
    out = root / "bocode/opt_problems/hpo/data"
    out.mkdir(parents=True, exist_ok=True)

    tables, tasks = {}, []
    for space in sorted(data):
        for dataset in sorted(data[space]):
            v = data[space][dataset]
            if len(v["X"]) < MIN_EVALS:
                continue
            X = np.asarray(v["X"], dtype=float)
            y = np.asarray(v["y"], dtype=float).ravel()
            dim = X.shape[1]
            if len(X) > MAX_POOL:
                rng = np.random.RandomState(0)
                idx = rng.choice(len(X), MAX_POOL, replace=False)
                X, y = X[idx], y[idx]
            tables[f"{space}_{dataset}"] = np.column_stack([X, y]).astype(np.float32)
            tasks.append((space, dataset, dim))
    np.savez_compressed(out / "hpob_data.npz", **tables)

    src = [_MODULE_HEADER]
    for space, dataset, dim in tasks:
        model = SPACE_MODEL.get(space, "model")
        src.append(
            f"\n\nclass HPOB_{space}_{dataset}(HPOBProblem):\n"
            f'    """{model} tuning (HPO-B search space {space}, dataset {dataset}), {dim} dims."""\n\n'
            f"    available_dimensions = {dim}\n"
            f'    task_key = "{space}_{dataset}"\n'
        )
    (root / "bocode/opt_problems/hpo/HPOB.py").write_text("".join(src))
    print(f"wrote hpob_data.npz + {len(tasks)} HPO-B classes")


if __name__ == "__main__":
    main()
